import React, { memo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { API_URLS } from "../constants";
import axios from "axios";
import { setLoader } from "../../redux";
import { useDispatch } from "react-redux";

const Totp = ({
  generateQr,
  setGenerateQr,
  setIsFirstTime,
  isFirstTime,
  fetchQrCode,
  userData,
}) => {
  const navigate = useNavigate();
  const dispatch = useDispatch();

  const [error, setError] = useState("");
  const [totp, setTOtp] = useState("");

  const handleChange = (e) => {
    const value = e.target.value;
    if (/^\d*$/.test(value)) {
      setTOtp(value);
      setError("");
    }
  };

  const handleTotpSubmit = async () => {
    if (!totp || totp.length !== 6) {
      setError("Please enter a valid 6-digit TOTP.");
      return;
    }
    console.log("totp", totp);
    dispatch(setLoader(true));

    setError("");
    try {
      if (userData) {
        const response = await axios.post(`${API_URLS.VERIFY_TOTP_URL}`, {
          identifier: userData.username,
          code: totp,
        });

        if (response?.status === 200 && response?.data?.success) {
          dispatch(setLoader(false));
          console.log("TOTP verification successful:", response.data);
          navigate("/dashboard");
        } else {
          setError(
            response?.data?.message || "Invalid TOTP. Please try again."
          );
        }
      }
    } catch (error) {
      dispatch(setLoader(false));

      console.error("Error during TOTP verification:", error?.response?.data);
      setError(
        error?.response?.data?.message ||
          "An error occurred during TOTP verification. Please try again."
      );
    }
  };

  const handleForgetTotp = () => {
    console.log("handleForgetTotp is clicked");
    setIsFirstTime(true);
    fetchQrCode(userData);
  };

  return (
    <div className="login-center">
      {isFirstTime ? (
        <div>
          <h2>Set up Two-Factor Authentication</h2>
          <p>Secure your account by enabling two-factor authentication.</p>
          <ol>
            <li>
              Open your authenticator app (e.g., Google Authenticator or Authy).
            </li>
            <li>Tap the '+' button to add a new account.</li>
            <li>
              Scan the QR code below or enter the provided secret key manually.
            </li>
          </ol>
          <div className=" flex justify-center mb-1.5">
            <img src={generateQr} alt="QR Code" />
          </div>
          <button
            type="button"
            className="totp-proceed-button"
            onClick={() => setIsFirstTime(false)}
          >
            Proceed
          </button>
        </div>
      ) : (
        <div>
          <h2>Verify Your Code</h2>
          <p>
            Enter the 6-digit code generated by your authenticator app to verify
            your setup.
          </p>
          <form>
            <input
              type="text"
              maxLength={6}
              placeholder="Enter TOTP"
              value={totp}
              onChange={handleChange}
            />
            <div className="login-center-options">
              <div className="error-div">{error}</div>
              <a
                href="#"
                className="forgot-pass-link"
                onClick={handleForgetTotp}
              >
                Forget TOTP
              </a>
            </div>
            <div className="login-center-buttons">
              <button
                className="opt-button"
                type="button"
                onClick={handleTotpSubmit}
              >
                Verify
              </button>
              <button
                className="opt-buttons"
                type="button"
                onClick={() => navigate("/")}
              >
                Go Back
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
};

export default Totp;
