import React, { memo, useState } from "react";
import { QRCodeCanvas } from "qrcode.react";

const Totp = () => {
  const [isFirstTime, setIsFirstTime] = useState(true);
  const [error, setError] = useState("");
  const [totp, setTOtp] = useState("");
  const secretKey = "YOUR_SECRET_KEY"; // Replace with server-generated secret key
  const totpUri = `otpauth://totp/YourAppName?secret=${secretKey}&issuer=YourAppName`;

  const handleChange = (e) => {
    setTOtp(e.target.value);
  };

  const handleSubmit = () => {
    if (totp.length !== 6) {
      setError("Please enter a valid 6-digit OTP.");
      return;
    }

    setError(""); // Clear errors

    // Handle OTP verification (API call, etc.)
    console.log("OTP entered:", totp);

    // Redirect after successful verification
    navigate("/dashboard"); // Replace with your target route
  };
  return (
    <div className="login-center">
      {isFirstTime ? (
        <div>
          <h2>Set up Two-Factor Authentication</h2>
          <p>Secure your account by enabling two-factor authentication.</p>
          <ol>
            <li>
              Open your authenticator app (e.g., Google Authenticator or Authy).
            </li>
            <li>Tap the '+' button to add a new account.</li>
            <li>
              Scan the QR code below or enter the provided secret key manually.
            </li>
          </ol>
          <div className="qr-code">
            <QRCodeCanvas value={totpUri} size={200} />
          </div>
          <button
            type="button"
            className="totp-proceed-button"
            onClick={() => setIsFirstTime(false)}
          >
            Proceed
          </button>
        </div>
      ) : (
        <div>
          <h2>Verify Your Code</h2>
          <p>
            Enter the 6-digit code generated by your authenticator app to verify
            your setup.
          </p>
          <form>
            <input
              type="text"
              maxLength={6}
              placeholder="Enter TOTP"
              value={totp}
              onChange={handleChange}
              required
            />
            <div className="login-center-options">
              <div className="error-div">{error}</div>
              <a href="#" className="forgot-pass-link">
                Resend OTP
              </a>
            </div>
            <div className="login-center-buttons">
              <button type="button" onClick={handleSubmit}>
                Verify
              </button>
              <button type="button" onClick={() => setIsFirstTime(true)}>
                Go Back
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
};

export default Totp;
